# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: spdkcsi-sc
provisioner: csi.spdk.io
parameters:
  fsType: ext4
  # QoS parameters are optional
  qosReadWriteIops: "0"
  qosReadWriteMbytes: "0"
  qosReadMbytes: "0"
  qosWriteMbytes: "0"
  csi.storage.k8s.io/provisioner-secret-name: spdkcsi-secret
  csi.storage.k8s.io/provisioner-secret-namespace: default
reclaimPolicy: Delete
volumeBindingMode: Immediate
